name: Multi Auto Commit

on:
  schedule:
    - cron: '*/2 * * * *'  # هر 2 دقیقه بررسی
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Random decision to commit
        run: |
          COUNT=$((RANDOM % 10 + 1))
          echo "Will try $COUNT commits today" >> log.txt

          for i in $(seq 1 $COUNT); do
            echo "update $i at $(date)" >> log.txt

            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .

            git commit -m "auto commit $i" || true
            git push || true

            sleep 5
          done
